apiVersion: v1
kind: Service
metadata:
  name: base-service
spec:
  selector:
    app: base
  ports:
    - port: 55390
      targetPort: 55390
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-deployment
  labels:
    app: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base
  template:
    metadata:
      labels:
        app: base
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: base
        image: will1233/base:v2
        volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage