apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: web
  ports:
    - port: 9527
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: will1233/web:v3